version: '3.7'
services:
    workspace:
        image: 'rushlowdev/php-cli:8.0-cli'
        volumes:
            - ./:/var/htdocs
        tty: true

    php-cli:
        build:
            context: ./.docker/php-cli
        volumes:
            - ./:/var/htdocs
